[package]
name = "load-tests-rust"
version = "0.1.0"
authors = ["Mykola Chekhovoi <ext-m.chekhovoi@here.com>"]
build="build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-ini = "0.13.0"
rand="0.7.2"
hdrhistogram = "6.3.4"

